Import("qtEnv dup reverted")

qtEnv.EnableQt5Modules(['QtCore','QtGui'])

if dup == 0: 
  qtEnv.Append(CPPPATH=['.'])

if reverted == 0:
  qtEnv.Program('aaa',['aaa.cpp','bbb.cpp'])
else:
  qtEnv.Program('aaa',['bbb.cpp','aaa.cpp'])

